joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

front_left_controller:
  type: position_controllers/JointPositionController
  joints:
    - motor_front_left_hip
    - motor_front_left_upper_leg
    - motor_front_left_lower_leg
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gains:
  #   motor_front_left_hip:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_front_left_upper_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_front_left_lower_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
front_right_controller:
  type: position_controllers/JointPositionController
  joints:
    - motor_front_right_hip
    - motor_front_right_upper_leg
    - motor_front_right_lower_leg
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gains:
  #   motor_front_right_hip:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_front_right_upper_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_front_right_lower_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
rear_left_controller:
  type: position_controllers/JointPositionController
  joints:
    - motor_back_left_hip
    - motor_back_left_upper_leg
    - motor_back_left_lower_leg
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gains:
  #   motor_back_left_hip:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_back_left_upper_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_back_left_lower_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
rear_right_controller:
  type: position_controllers/JointPositionController
  joints:
    - motor_back_right_hip
    - motor_back_right_upper_leg
    - motor_back_right_lower_leg
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gains:
  #   motor_back_right_hip:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_back_right_upper_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   motor_back_right_lower_leg:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1